language: python

python:
  - 2.6
  - 2.7

install:
  - pip install kitchen coveralls nose webtest --use-mirrors
  - python setup.py install

script:
  - nosetests -q --with-coverage --cover-erase --cover-package=bodhi

after_success:
  - coveralls
